/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.db;

/**
 *
 * @author Hogar
 */
public class Creacion extends javax.swing.JFrame {

    /**
     * Creates new form Creacion
     */
    public Creacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        conjunto = new javax.swing.JButton();
        bloque = new javax.swing.JButton();
        apto = new javax.swing.JButton();
        parqueadero = new javax.swing.JButton();
        espacioComun = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        persona = new javax.swing.JButton();
        valoresGlo = new javax.swing.JButton();
        reserva = new javax.swing.JButton();
        pagoReserva = new javax.swing.JButton();
        pagoCuota = new javax.swing.JButton();
        cuota = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        conjunto.setText("Conjunto");
        conjunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conjuntoActionPerformed(evt);
            }
        });
        jPanel1.add(conjunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        bloque.setText("Bloque");
        bloque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloqueActionPerformed(evt);
            }
        });
        jPanel1.add(bloque, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        apto.setText("Apartamento");
        apto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aptoActionPerformed(evt);
            }
        });
        jPanel1.add(apto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        parqueadero.setText("Parqueadero");
        parqueadero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parqueaderoActionPerformed(evt);
            }
        });
        jPanel1.add(parqueadero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        espacioComun.setText("Espacio Comun");
        espacioComun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espacioComunActionPerformed(evt);
            }
        });
        jPanel1.add(espacioComun, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 200, 340));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        persona.setText("Persona");
        jPanel2.add(persona, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        valoresGlo.setText("Valores Globales");
        valoresGlo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valoresGloActionPerformed(evt);
            }
        });
        jPanel2.add(valoresGlo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        reserva.setText("Reserva");
        reserva.setToolTipText("");
        jPanel2.add(reserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        pagoReserva.setText("Pago Reserva");
        jPanel2.add(pagoReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        pagoCuota.setText("Pago Cuota");
        jPanel2.add(pagoCuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        cuota.setText("Cuota");
        jPanel2.add(cuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        jButton2.setText("Telefono");
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 250, 340));

        jButton1.setText("Continuar");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void parqueaderoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parqueaderoActionPerformed
        
    }//GEN-LAST:event_parqueaderoActionPerformed

    private void espacioComunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espacioComunActionPerformed
       
    }//GEN-LAST:event_espacioComunActionPerformed

    private void conjuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conjuntoActionPerformed
     
    }//GEN-LAST:event_conjuntoActionPerformed

    private void aptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aptoActionPerformed

    }//GEN-LAST:event_aptoActionPerformed

    private void bloqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloqueActionPerformed
        
    }//GEN-LAST:event_bloqueActionPerformed

    private void valoresGloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valoresGloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valoresGloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Creacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apto;
    private javax.swing.JButton bloque;
    private javax.swing.JButton conjunto;
    private javax.swing.JButton cuota;
    private javax.swing.JButton espacioComun;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton pagoCuota;
    private javax.swing.JButton pagoReserva;
    private javax.swing.JButton parqueadero;
    private javax.swing.JButton persona;
    private javax.swing.JButton reserva;
    private javax.swing.JButton valoresGlo;
    // End of variables declaration//GEN-END:variables
}
