/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administradorpropiedadhorizontal;

/**
 *
 * @author SEBASTIAN
 */
public class JFrameConjunto extends javax.swing.JFrame {

    /**
     * Creates new form JFrameConjunto
     */
    public JFrameConjunto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generalesConjunto = new javax.swing.JPanel();
        labelnombreCjto = new javax.swing.JLabel();
        labelidCjto = new javax.swing.JLabel();
        labelctaBanc = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        idConjunto = new javax.swing.JSpinner();
        cuentaBanco = new javax.swing.JSpinner();
        datosGlobales = new javax.swing.JPanel();
        labelCuota = new javax.swing.JLabel();
        labelDescuento = new javax.swing.JLabel();
        labelDiasDesc = new javax.swing.JLabel();
        labelMora = new javax.swing.JLabel();
        valorCuotaAdmin = new javax.swing.JSpinner();
        tazaDescuento = new javax.swing.JSpinner();
        diasDescuento = new javax.swing.JSpinner();
        tasaMora = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        crear = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Conjunto");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        generalesConjunto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelnombreCjto.setText("Inserte el nombre de Conjunto");
        generalesConjunto.add(labelnombreCjto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        labelidCjto.setText("Inserte la identificación del Conjunto");
        generalesConjunto.add(labelidCjto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        labelctaBanc.setText("Inserte el numero de la cuenta bancaria del Conjunto");
        generalesConjunto.add(labelctaBanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        generalesConjunto.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 321, -1));

        idConjunto.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9999, 1));
        generalesConjunto.add(idConjunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, -1));

        cuentaBanco.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99999999, 1));
        generalesConjunto.add(cuentaBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, -1));

        getContentPane().add(generalesConjunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 670, 120));

        datosGlobales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCuota.setText("Inserte el valor de la cuota de administración mensual");
        datosGlobales.add(labelCuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        labelDescuento.setText("Inserte la tasa de descuento de la cuota de administración");
        datosGlobales.add(labelDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        labelDiasDesc.setText("Inserte el numero de días hasta que se apica el descuento");
        datosGlobales.add(labelDiasDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        labelMora.setText("Inserte la tasa de mora de la cuota de administración");
        datosGlobales.add(labelMora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        valorCuotaAdmin.setModel(new javax.swing.SpinnerNumberModel(1, 1, 999999, 1));
        datosGlobales.add(valorCuotaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        tazaDescuento.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.01f), Float.valueOf(0.01f), Float.valueOf(100.0f), Float.valueOf(0.01f)));
        datosGlobales.add(tazaDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, -1, -1));

        diasDescuento.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        datosGlobales.add(diasDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 100, -1));

        tasaMora.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.01f), Float.valueOf(0.01f), Float.valueOf(100.0f), Float.valueOf(0.01f)));
        datosGlobales.add(tasaMora, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));

        jLabel1.setText("%");
        datosGlobales.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, -1, -1));

        jLabel2.setText("%");
        datosGlobales.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, -1, -1));

        getContentPane().add(datosGlobales, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 670, 130));

        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });
        getContentPane().add(crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, -1));

        actualizar.setText("Actualizar");
        getContentPane().add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Datos generales del Conjunto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameConjunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameConjunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameConjunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameConjunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameConjunto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton crear;
    private javax.swing.JSpinner cuentaBanco;
    private javax.swing.JPanel datosGlobales;
    private javax.swing.JSpinner diasDescuento;
    private javax.swing.JPanel generalesConjunto;
    private javax.swing.JSpinner idConjunto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelCuota;
    private javax.swing.JLabel labelDescuento;
    private javax.swing.JLabel labelDiasDesc;
    private javax.swing.JLabel labelMora;
    private javax.swing.JLabel labelctaBanc;
    private javax.swing.JLabel labelidCjto;
    private javax.swing.JLabel labelnombreCjto;
    private javax.swing.JTextField nombre;
    private javax.swing.JSpinner tasaMora;
    private javax.swing.JSpinner tazaDescuento;
    private javax.swing.JSpinner valorCuotaAdmin;
    // End of variables declaration//GEN-END:variables
}
