/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administradorpropiedadhorizontal;

/**
 *
 * @author SEBASTIAN
 */
public class JFrameApartamento extends javax.swing.JFrame {

    String opcion;
    
    /**
     * Creates new form JFrameApartamento
     * @param opcion
     */
    public JFrameApartamento(String opcion) {
        initComponents();
        this.opcion = opcion;
        if(opcion.equals("Actualizar")){
            crear.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelIdApt = new javax.swing.JLabel();
        labelAreaApt = new javax.swing.JLabel();
        labelPisoApt = new javax.swing.JLabel();
        labelCoefApt = new javax.swing.JLabel();
        idApartamento = new javax.swing.JSpinner();
        areaPrivada = new javax.swing.JSpinner();
        pisoApartamento = new javax.swing.JSpinner();
        coeficienteAdmin = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        labelBloque = new javax.swing.JLabel();
        labelApartamento = new javax.swing.JLabel();
        listBloque = new javax.swing.JComboBox<>();
        listApartamento = new javax.swing.JComboBox<>();
        crear = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Apartamento");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelIdApt.setText("Digite la identificación del Apartamento:");
        jPanel1.add(labelIdApt, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 16, -1, -1));

        labelAreaApt.setText("Digite el tamaño del Área Privada:");
        jPanel1.add(labelAreaApt, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 42, -1, -1));

        labelPisoApt.setText("Seleccione el piso del Apartamento:");
        jPanel1.add(labelPisoApt, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 71, -1, -1));

        labelCoefApt.setText("Digite su coeficiente de administración:");
        jPanel1.add(labelCoefApt, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 100, -1, -1));

        idApartamento.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9999, 1));
        jPanel1.add(idApartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 13, -1, -1));

        areaPrivada.setModel(new javax.swing.SpinnerNumberModel(1, 1, 999, 1));
        jPanel1.add(areaPrivada, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 42, -1, -1));

        pisoApartamento.setModel(new javax.swing.SpinnerNumberModel(1, 1, 999, 1));
        jPanel1.add(pisoApartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 71, -1, -1));

        coeficienteAdmin.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.01f), Float.valueOf(0.01f), Float.valueOf(10.0f), Float.valueOf(0.01f)));
        jPanel1.add(coeficienteAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 107, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Datos Apartamento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        labelBloque.setText("Seleccione el Bloque del apartamento:");
        getContentPane().add(labelBloque, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 52, -1, -1));

        labelApartamento.setText("Seleccione la identificación del Responsable:");
        getContentPane().add(labelApartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 81, -1, -1));

        listBloque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listBloque.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listBloqueItemStateChanged(evt);
            }
        });
        listBloque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listBloqueActionPerformed(evt);
            }
        });
        getContentPane().add(listBloque, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 49, -1, -1));

        listApartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listApartamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listApartamentoItemStateChanged(evt);
            }
        });
        getContentPane().add(listApartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 78, -1, -1));

        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });
        getContentPane().add(crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actualizarActionPerformed

    private void listBloqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listBloqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listBloqueActionPerformed

    private void listBloqueItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listBloqueItemStateChanged
        // TODO add your handling code here:
        if(opcion.equals("Actualizar")){
            
        }
        verificar();
    }//GEN-LAST:event_listBloqueItemStateChanged

    private void listApartamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listApartamentoItemStateChanged
        // TODO add your handling code here:
        if(opcion.equals("Actualizar")){
            
        }
        verificar();
    }//GEN-LAST:event_listApartamentoItemStateChanged

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearActionPerformed

    public void verificar(){
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameApartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameApartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameApartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameApartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameApartamento("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JSpinner areaPrivada;
    private javax.swing.JSpinner coeficienteAdmin;
    private javax.swing.JButton crear;
    private javax.swing.JSpinner idApartamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelApartamento;
    private javax.swing.JLabel labelAreaApt;
    private javax.swing.JLabel labelBloque;
    private javax.swing.JLabel labelCoefApt;
    private javax.swing.JLabel labelIdApt;
    private javax.swing.JLabel labelPisoApt;
    private javax.swing.JComboBox<String> listApartamento;
    private javax.swing.JComboBox<String> listBloque;
    private javax.swing.JSpinner pisoApartamento;
    // End of variables declaration//GEN-END:variables
}
