/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import logica.Conjunto;

/**
 *
 * @author Hogar
 */
public class Creacion extends javax.swing.JFrame {

    Conjunto conjunto;
    
    /**
     * Creates new form Creacion
     */
    public Creacion(Conjunto conjunto) {
        initComponents();
        this.conjunto = conjunto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bloque = new javax.swing.JPanel();
        apto = new javax.swing.JButton();
        parqueadero = new javax.swing.JButton();
        espacioComun = new javax.swing.JButton();
        Bloque = new javax.swing.JButton();
        reserva = new javax.swing.JButton();
        pagoEspacio = new javax.swing.JButton();
        persona = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cuota = new javax.swing.JButton();
        pagoCuota = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bloque.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        apto.setText("Apartamento");
        apto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aptoActionPerformed(evt);
            }
        });
        bloque.add(apto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        parqueadero.setText("Parqueadero");
        parqueadero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parqueaderoActionPerformed(evt);
            }
        });
        bloque.add(parqueadero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        espacioComun.setText("Espacio Comun");
        espacioComun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espacioComunActionPerformed(evt);
            }
        });
        bloque.add(espacioComun, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        Bloque.setText("Bloque");
        Bloque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloqueActionPerformed(evt);
            }
        });
        bloque.add(Bloque, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        reserva.setText("Reserva");
        reserva.setToolTipText("");
        reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservaActionPerformed(evt);
            }
        });
        bloque.add(reserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        pagoEspacio.setText("Pago Espacio");
        pagoEspacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagoEspacioActionPerformed(evt);
            }
        });
        bloque.add(pagoEspacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        persona.setText("Persona");
        bloque.add(persona, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jButton2.setText("Telefono");
        bloque.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        cuota.setText("Cuota");
        bloque.add(cuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        pagoCuota.setText("Pago Cuota");
        bloque.add(pagoCuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        getContentPane().add(bloque, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, 330));

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 110, 330));

        jLabel1.setFont(new java.awt.Font("Tekton Pro Cond", 0, 24)); // NOI18N
        jLabel1.setText("Creacion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void parqueaderoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parqueaderoActionPerformed
       new JFrameParqueadero(conjunto).setVisible(true);
    }//GEN-LAST:event_parqueaderoActionPerformed

    private void espacioComunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espacioComunActionPerformed
       new JFrameEspacioComun(conjunto).setVisible(true);
    }//GEN-LAST:event_espacioComunActionPerformed

    private void aptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aptoActionPerformed

    }//GEN-LAST:event_aptoActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void BloqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloqueActionPerformed
        new JFrameBloque(conjunto).setVisible(true);
    }//GEN-LAST:event_BloqueActionPerformed

    private void reservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservaActionPerformed
        new JFrameReserva(conjunto).setVisible(true);
    }//GEN-LAST:event_reservaActionPerformed

    private void pagoEspacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagoEspacioActionPerformed
        new JFramePagoEspacio(conjunto, "Registrar").setVisible(true);
    }//GEN-LAST:event_pagoEspacioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bloque;
    private javax.swing.JButton apto;
    private javax.swing.JPanel bloque;
    private javax.swing.JButton cuota;
    private javax.swing.JButton espacioComun;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pagoCuota;
    private javax.swing.JButton pagoEspacio;
    private javax.swing.JButton parqueadero;
    private javax.swing.JButton persona;
    private javax.swing.JButton reserva;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
