package presentacion;

import logica.Conjunto;

/**
 *
 * @author 
 */
public class EliminarModificar extends javax.swing.JFrame {

    Conjunto conjunto;
    
    /**
     * Creates new form Actualizar
     * @param conjunto
     */
    public EliminarModificar(Conjunto conjunto) {
        initComponents();
        this.conjunto = conjunto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        modificar = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        valoresGloabalesM = new javax.swing.JButton();
        apartamentoM = new javax.swing.JButton();
        espacioComunM = new javax.swing.JButton();
        conjuntoM = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        eliminar = new javax.swing.JLabel();
        pagoEspacioD = new javax.swing.JButton();
        personaD = new javax.swing.JButton();
        telefonoD = new javax.swing.JButton();
        pagoCuaotaD = new javax.swing.JButton();
        cuotaD = new javax.swing.JButton();
        reservaD = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        modificar.setText("Modificar");
        jPanel1.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jButton5.setText("Pago Reserva");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 110, -1));

        jButton6.setText("Persona");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, -1));

        jButton9.setText("Telefono");
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 110, -1));

        jButton8.setText("Pago Cuota");
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, -1));

        jButton7.setText("Cuota");
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 110, -1));

        valoresGloabalesM.setText("Valores Globales");
        valoresGloabalesM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valoresGloabalesMActionPerformed(evt);
            }
        });
        jPanel1.add(valoresGloabalesM, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        apartamentoM.setText("Apartamento");
        apartamentoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apartamentoMActionPerformed(evt);
            }
        });
        jPanel1.add(apartamentoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 120, -1));

        espacioComunM.setText("Espacio Comun");
        jPanel1.add(espacioComunM, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 120, -1));

        conjuntoM.setText("Conjunto");
        jPanel1.add(conjuntoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 350, 280));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eliminar.setText("Eliminar");
        jPanel2.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 10, 70, -1));

        pagoEspacioD.setText("Pago Espacio");
        pagoEspacioD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagoEspacioDActionPerformed(evt);
            }
        });
        jPanel2.add(pagoEspacioD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        personaD.setText("Persona");
        jPanel2.add(personaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 90, -1));

        telefonoD.setText("Telefono");
        jPanel2.add(telefonoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 95, -1));

        pagoCuaotaD.setText("Pago Cuota");
        jPanel2.add(pagoCuaotaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        cuotaD.setText("Cuota");
        jPanel2.add(cuotaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 95, -1));

        reservaD.setText("Reserva");
        reservaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservaDActionPerformed(evt);
            }
        });
        jPanel2.add(reservaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 89, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 220));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 110, -1));

        salir.setText("Volver");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 70, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apartamentoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apartamentoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apartamentoMActionPerformed

    private void valoresGloabalesMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valoresGloabalesMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valoresGloabalesMActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void pagoEspacioDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagoEspacioDActionPerformed
        new JFramePagoEspacio(conjunto, "Eliminar").setVisible(true);
    }//GEN-LAST:event_pagoEspacioDActionPerformed

    private void reservaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservaDActionPerformed
        new JFrameReservaDelete(conjunto).setVisible(true);
    }//GEN-LAST:event_reservaDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apartamentoM;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton conjuntoM;
    private javax.swing.JButton cuotaD;
    private javax.swing.JLabel eliminar;
    private javax.swing.JButton espacioComunM;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel modificar;
    private javax.swing.JButton pagoCuaotaD;
    private javax.swing.JButton pagoEspacioD;
    private javax.swing.JButton personaD;
    private javax.swing.JButton reservaD;
    private javax.swing.JButton salir;
    private javax.swing.JButton telefonoD;
    private javax.swing.JButton valoresGloabalesM;
    // End of variables declaration//GEN-END:variables
}
