/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.util.logging.Level;
import java.util.logging.Logger;
import logica.Conjunto;
import logica.Inmobiliaria;
import logica.Reserva;
import util.CaException;

/**
 *
 * @author Hogar
 */
public class JFrameReservaDelete extends javax.swing.JFrame {

    Conjunto conjunto;
    Inmobiliaria inmobiliaria = new Inmobiliaria();
    Reserva reserva;

    /**
     * Creates new form JFrameReservaDelete
     */
    public JFrameReservaDelete(Conjunto conjunto) {
        initComponents();
        this.conjunto = conjunto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumReserva1 = new javax.swing.JLabel();
        spnNumReserva = new javax.swing.JSpinner();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumReserva1.setText("Número unico de reserva:");
        getContentPane().add(lblNumReserva1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 51, 166, -1));

        spnNumReserva.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9999, 1));
        getContentPane().add(spnNumReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 110, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        reserva = new Reserva((int) spnNumReserva.getValue());
        try {
            inmobiliaria.eliminarReserva(reserva);
        } catch (CaException ex) {
            Logger.getLogger(JFrameReservaDelete.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel lblNumReserva1;
    private javax.swing.JSpinner spnNumReserva;
    // End of variables declaration//GEN-END:variables
}
