/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logica.Conjunto;
import logica.EspacioComun;
import logica.Inmobiliaria;
import util.CaException;

/**
 *
 * @author Hogar
 */
public class JFrameEspacioComun extends javax.swing.JFrame {

    Conjunto conjunto;
    EspacioComun espacio;
    Inmobiliaria inmobiliaria = new Inmobiliaria();

    /**
     * Creates new form JFrameEspacioComun
     */
    public JFrameEspacioComun(Conjunto conjunto) {
        initComponents();
        this.conjunto = conjunto;
        lblEstado.setVisible(false);
        boxEstado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumEC = new javax.swing.JLabel();
        lblTipoEC = new javax.swing.JLabel();
        lblValorAlqu = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        spnNumEC = new javax.swing.JSpinner();
        listaEC = new javax.swing.JComboBox<>();
        spnValor = new javax.swing.JSpinner();
        boxEstado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumEC.setText("Número unico de Espacio:");
        getContentPane().add(lblNumEC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 210, -1));

        lblTipoEC.setText("Tipo de Espacio Comun:");
        getContentPane().add(lblTipoEC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 180, -1));

        lblValorAlqu.setText("Valor del Alquiler:");
        getContentPane().add(lblValorAlqu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 140, -1));

        lblEstado.setText("Estado:");
        lblEstado.setToolTipText("");
        getContentPane().add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 150, 20));

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 80, -1));

        spnNumEC.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9999, 1));
        getContentPane().add(spnNumEC, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 70, -1));

        listaEC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salon", "Parqueadero Visitante", "BBQ" }));
        getContentPane().add(listaEC, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 170, -1));

        spnValor.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(1L), Long.valueOf(1L), Long.valueOf(9999999999L), Long.valueOf(1L)));
        getContentPane().add(spnValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 170, -1));

        boxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Ocupado" }));
        getContentPane().add(boxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed

        try {
            String tipo = "";
            if (listaEC.getSelectedItem().equals("Salon")) {
                tipo = "SALON";
            } else if (listaEC.getSelectedItem().equals("Parqueadero Visitante")) {
                tipo = "PARQ_VSNTE";
            } else if (listaEC.getSelectedItem().equals("BBQ")) {
                tipo = "BBQ";
            }

            espacio = new EspacioComun((int) spnNumEC.getValue(), tipo, (Long) spnValor.getValue(), (int) conjunto.getK_codigo(), "T");
            inmobiliaria.incluirEspacioComun(espacio);
            
            JOptionPane.showMessageDialog(this, "Espacio añadido exitosamente", "Operacion realizada", JOptionPane.INFORMATION_MESSAGE);
        } catch (CaException ex) {
            Logger.getLogger(JFrameEspacioComun.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxEstado;
    private javax.swing.JButton btnCrear;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNumEC;
    private javax.swing.JLabel lblTipoEC;
    private javax.swing.JLabel lblValorAlqu;
    private javax.swing.JComboBox<String> listaEC;
    private javax.swing.JSpinner spnNumEC;
    private javax.swing.JSpinner spnValor;
    // End of variables declaration//GEN-END:variables
}
